robot:
  port: /dev/tty.usbmodem1102
  cameras:
    table:
      type: opencv
      index_or_path: 1
      width: 1280
      height: 720
      fps: 20
safety:
  ee_limits_file: robot/safety/ee_limits.yaml